version: '3'
services:
  auth:
    environment:
      JAVA_OPTS: '-Xmx1536m -Dspring.profiles.active=default,mariadb'
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://database:3306/auth?createDatabaseIfNotExist=true'
  database:
    image: mariadb:10.4.12
    command: --lower_case_table_names=1 --sql_mode=ANSI --character_set_server=utf8mb4
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - databasenet
    ports:
      - '33270:3306'
    restart: always
    tty: true