version: '3'
services:
  adminweb:
    depends_on:
      - admingateway
      - tutorialgettingstarted
  localsolr:
    environment:
      SOLR_HOST: 'localsolr:8983'
  tutorialgettingstarted:
    depends_on:
      - mongo
      - postgres
      - config
      - localkafka
      - admingateway
      - localsolr
    env_file:
      - common-environment.env
    environment:
      BROADLEAF_ASSET_INTERNAL_CONTENTPROVIDERURLPREFIX: 'https://localhost:8447/'
      BROADLEAF_ASSET_INTERNAL_PREPENDREQUESTCONTEXTPATH: 'false'
      BROADLEAF_ASSET_MONGODB_URI: 'mongodb://mongo:27017/asset'
      BROADLEAF_ASSET_PROVIDER_CONTENTURLPREFIX: 'https://localhost:8447/content'
      BROADLEAF_CAMPAIGN_MONGODB_URI: 'mongodb://mongo:27017/campaign'
      BROADLEAF_CART_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/broadleaf?currentSchema=cart'
      BROADLEAF_CATALOG_MONGODB_URI: 'mongodb://mongo:27017/catalog'
      BROADLEAF_CUSTOMER_MONGODB_URI: 'mongodb://mongo:27017/customer'
      BROADLEAF_DATAIMPORT_MONGODB_URI: 'mongodb://mongo:27017/import'
      BROADLEAF_INDEXER_MONGODB_URI: 'mongodb://mongo:27017/indexer'
      BROADLEAF_MENU_MONGODB_URI: 'mongodb://mongo:27017/menu'
      BROADLEAF_METADATA_MONGODB_URI: 'mongodb://mongo:27017/metadata'
      BROADLEAF_NAVIGATION_MONGODB_URI: 'mongodb://mongo:27017/admin-navigation'
      BROADLEAF_OFFER_MONGODB_URI: 'mongodb://mongo:27017/offer'
      BROADLEAF_PERSONALIZATION_MONGODB_URI: 'mongodb://mongo:27017/personalization'
      BROADLEAF_PRICING_MONGODB_URI: 'mongodb://mongo:27017/pricing'
      BROADLEAF_SANDBOX_MONGODB_URI: 'mongodb://mongo:27017/sandbox'
      BROADLEAF_SCHEDULEDJOB_MONGODB_URI: 'mongodb://mongo:27017/scheduledjob'
      BROADLEAF_SEARCH_MONGODB_URI: 'mongodb://mongo:27017/search'
      BROADLEAF_SEARCH_SOLR_SERVER_CHROOT: '/solr'
      BROADLEAF_SEARCH_SOLR_SERVER_HOST: 'zk:2181'
      BROADLEAF_TENANT_MONGODB_URI: 'mongodb://mongo:27017/tenant'
      DEBUG_PORT: 8004
      JAVA_OPTS: '-Xmx1536m -DzkACLProvider=org.apache.solr.common.cloud.VMParamsAllAndReadonlyDigestZkACLProvider -DzkCredentialsProvider=org.apache.solr.common.cloud.VMParamsSingleSetCredentialsDigestZkCredentialsProvider -DzkDigestUsername=readonly-user -DzkDigestPassword=CHANGEME-READONLY-PASSWORD'
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
    image: repository.broadleafcommerce.com:5001/broadleaf/tutorial-getting-started:latest-snapshot
    networks:
      - mongonet
      - kafkanet
      - backend
      - solrnet
      - postgresnet
    ports:
      - '8447:8447'
      - '8004:8004'
    tty: true