broadleaf:
  database:
    provider: jpa
  adminnavigation:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=adminnavigation'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/admin-navigation-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/admin-navigation.db.changelog-master.yaml'
      liquibase-schema: public
  adminuser:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=adminuser'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/admin-user-sample-data.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/admin-user.db.changelog-master.yaml'
      liquibase-schema: public
  asset:
    internal:
      content-provider-url-prefix: 'https://localhost:8447/'
      prepend-request-context-path: false
    data:
      load-on-startup: true
      files:
        - path: classpath:__initial-data.zip
          context:
            tenant-id: 5DF1363059675161A85F576D
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=asset'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
    provider:
      contentUrlPrefix: 'https://localhost:8447/content'
    liquibase:
      change-log: 'classpath:/db/changelog/asset.db.changelog-master.yaml'
      liquibase-schema: public
  campaign:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=campaign'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/campaign-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/campaign.db.changelog-master.yaml'
      liquibase-schema: public
  cart:
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=cart'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
    jpa:
      hibernate:
        ddl-auto: create
      open-in-view: false
    liquibase:
      change-log: 'classpath:/db/changelog/cart.db.changelog-master.yaml'
      liquibase-schema: public
  cartoperation:
    anonymouscart:
      application-id-included-in-cookie-name: true
    campaignprovider:
      url: 'https://localhost:8447'
    cartprovider:
      url: 'https://localhost:8447'
    catalogprovider:
      url: 'https://localhost:8447'
    offerprovider:
      url: 'https://localhost:8447'
    pricingprovider:
      url: 'https://localhost:8447'
    walletprovider:
      url: 'https://localhost:8447'
  catalog:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=catalog'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/catalog-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/catalog.db.changelog-master.yaml'
      liquibase-schema: public
  catalogbrowse:
    catalogprovider:
      url: 'https://localhost:8447'
    pricingprovider:
      url: 'https://localhost:8447'
  common:
    data:
      route:
        enabled: true
    policy:
      validation:
        enforce: true
  customer:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=customer'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/customer-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/customer.db.changelog-master.yaml'
      liquibase-schema: public
  dataimport:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=import'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
    liquibase:
      change-log: 'classpath:/db/changelog/import.db.changelog-master.yaml'
      liquibase-schema: public
  image:
    availableEffects: 'crop, resize, scale, thumbnail, unsharp'
  indexer:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=indexer'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
    liquibase:
      change-log: 'classpath:/db/changelog/indexer.db.changelog-master.yaml'
      liquibase-schema: public
    catalog:
      service:
        endpoint: 'https://localhost:8447'
    customer:
      service:
        endpoint: 'https://localhost:8447'
    search:
      service:
        endpoint: 'https://localhost:8447'
  menu:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=menu'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/menu-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/menu.db.changelog-master.yaml'
      liquibase-schema: public
  metadata:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=metadata'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
    liquibase:
      change-log: 'classpath:/db/changelog/metadata.db.changelog-master.yaml'
      liquibase-schema: public
  offer:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=offer'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/offer-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/offer.db.changelog-master.yaml'
      liquibase-schema: public
  payment:
    gateway:
      passthrough-transactions:
        active: true
  persistence:
    retry:
      developerMode: true
  personalization:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=personalization'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/personalization-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/personalization.db.changelog-master.yaml'
      liquibase-schema: public
  pricing:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=pricing'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/pricing-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/pricing.db.changelog-master.yaml'
      liquibase-schema: public
  resource:
    security:
      oauth2:
        defaultAllowAllAnonymous: false
  sandbox:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=sandbox'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/sandbox-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/sandbox.db.changelog-master.yaml'
      liquibase-schema: public
  scheduledjob:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=scheduledjob'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/scheduled-job-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/scheduled-job.db.changelog-master.yaml'
      liquibase-schema: public
  search:
    catalog:
      primaryAlias: catalog_alias_1
      secondaryAlias: catalog_alias_2
    customer:
      primaryAlias: customer_alias_1
      secondaryAlias: customer_alias_2
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=search'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/search-catalog-data-jpa.sql'
        - 'classpath:/search-customer-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/search.db.changelog-master.yaml'
      liquibase-schema: public
    solr:
      boost:
        phraseBoost: 3
        phraseExactBoost: 4
        phraseSlop: 2
        wordBoost: 2
      server:
        chroot: /solr
        host: 'localhost:2181'
        password: SolrRocks
        user-name: indexer
    spell-check:
      config:
        PRODUCT:
          autoCorrectQuery: true
          showSuggestionQueryHitCount: true
          spellCheckEnabled: true
          spellCheckQuery: true
          suggestedQueryCount: 1
          suggestionCount: 1
          suggestionQueryCollationTries: 1
  tenant:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      initialization-mode: always
      platform: postgres
      url: 'jdbc:postgresql://localhost:5432/broadleaf?currentSchema=tenant'
      username: broadleaf
      password: demo
      hikari:
        maximumPoolSize: 2
      data:
        - 'classpath:/tenant-data-jpa.sql'
    liquibase:
      change-log: 'classpath:/db/changelog/tenant.db.changelog-master.yaml'
      liquibase-schema: public
    global:
      allowed-locales:
        - en_US
        - en
        - en_GB
        - es
        - es_ES
        - es_MX
        - fr
        - fr_FR
    urlresolver:
      application:
        port: 8456
      admin:
        port: 8446
server:
  port: 8447
  servlet:
    context-path: /
  ssl:
    key-password: keypass
    key-store: 'classpath:local.keystore'
    key-store-password: storepass
spring:
  integration:
    jdbc:
      initialize-schema: always
  cloud:
    bus:
      enabled: false
  datasource:
    initialization-mode: never
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database: postgresql
  messages:
    useCodeAsDefaultMessage: true
  security:
    oauth2:
      client:
        provider:
          catalog:
            token-uri: 'https://localhost:8443/auth/oauth/token'
          customer:
            token-uri: 'https://localhost:8443/auth/oauth/token'
          search:
            token-uri: 'https://localhost:8443/auth/oauth/token'
        registration:
          catalog:
            authorization-grant-type: client_credentials
            client-id: catalog
            client-secret: catalog_secret
          customer:
            authorization-grant-type: client_credentials
            client-id: customer
            client-secret: customer_secret
          search:
            authorization-grant-type: client_credentials
            client-id: search
            client-secret: search_secret
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 20MB
      resolve-lazily: true
  thymeleaf:
    cache: false